replicaCount: 1
strategyType: Recreate

image:
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
imagePullSecrets: []

nfs:
  server: 2600:52:7:76::108
  path: /data/nfshare
  mountOptions:
  volumeName: nfs-client-root
  reclaimPolicy: Retain

storageClass:
  name: ava-nfs-client-sc        
  create: true
  provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
  defaultClass: true
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  archiveOnDelete: true
  onDelete:
  pathPattern:

  # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  accessModes: ReadWriteOnce

  # Set volume bindinng mode - Immediate or WaitForFirstConsumer
  volumeBindingMode: Immediate

  # Storage class annotations
  annotations: {}

#leaderElection:
  # When set to false leader election will be disabled
  #  enabled: true

podAnnotations: {}

## Set pod priorityClassName
# priorityClassName: ""

securityContext:
 fsGroup: 1000
 runAsUser: 1000

serviceAccount:
  create: true
  annotations: {}
  name: nfs-client-provisioner

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

# Additional labels for any resource created
labels: nfs-client-provisioner
